---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./cert-manager/controller
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: infrastructure
  timeout: 3m0s
  wait: true
