---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: deluge
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn
    - name: cert-manager
    - name: nfs-provisioner
  interval: 30m0s
  path: ./deluge
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: seedbox
  timeout: 3m0s
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
