---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: k0s
  url: https://github.com/logikdev-kubernetes/infrastructure
