---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  dependsOn:
    - name: certs
  interval: 30m0s
  path: ./longhorn
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: infrastructure
  timeout: 3m0s
  wait: true
  