---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openldap
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn
  interval: 30m0s
  path: ./openldap
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: infrastructure
  timeout: 3m0s
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
