---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redis
  namespace: flux-system
spec:
  dependsOn:
    - name: certs
  interval: 30m0s
  path: ./redis
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: databases
  timeout: 3m0s
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
