---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: seedbox
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/logikdev-kubernetes/seedbox
  secretRef:
    name: bearer-token-auth
